"""initial

Revision ID: 533ca4a329a1
Revises: fe8696bd4f87
Create Date: 2023-09-08 01:12:58.206472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533ca4a329a1'
down_revision: Union[str, None] = 'fe8696bd4f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_lookup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_lookup',
    sa.Column('grade_id', sa.INTEGER(), nullable=False),
    sa.Column('grade_letter', sa.VARCHAR(), nullable=True),
    sa.Column('grade_value', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('grade_letter')
    )
    # ### end Alembic commands ###
